name: "SAD experiment"
device: "cuda"

training_args:
  type: TrainingArguments

  args:
    n_steps: 8
    learning_rate: 0.01
    eps: 0.0000001
    eval_strategy: "step"
    eval_steps: 1
    update_per_steps: 16

model_args:
  type: QOP

  args:
    dim: 13
    std: 1
    lambda_2: 3
    lambda_3: 1
    verbose: 0
    p_norm: inf
    sinkhorn_maxIter: 20
    tol: 0.00001
    alpha: null
    beta: null

data_args:
  type: SADDataset

  args: 
    train_path: "../drive/MyDrive/dataset/project-2/SAD/Train_Arabic_Digit.txt"
    test_path: "../drive/MyDrive/dataset/project-2/SAD/Test_Arabic_Digit.txt"

    num_per_class: 50

trainer:
  type: Trainer

  compile: True # use PyTorch 2.0 to compile the model to be faster

  epochs: 1000
  save_dir: saved/
  save_period: 10
  verbosity: 1

  visual_tool: wandb
  project: nlps23

  api_key_file: ./configs/api/tuanlda78202
  entity: tuanlda78202